blank_issues_enabled: false
contact_links:
  - name: 💬 Hỏi đáp & Thảo luận Cộng đồng
    url: https://github.com/nguyenlocthanh796/mitv-vn-setup/discussions
    about: Đặt câu hỏi và giao lưu kinh nghiệm tối ưu tivi Xiaomi cùng cộng đồng.
